select * from customer


--Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(Purchase_Amount) as Revenue 
from customer 
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,Purchase_Amount 
from customer
where discount_applied = 'Yes' and
 Purchase_Amount >= (select avg(Purchase_Amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?
select top 5  item_purchased,round(avg(review_rating),2)as avg_Product_rating
from customer
where review_rating is not null
group by item_purchased 
order by avg_Product_rating desc

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type,
avg(Purchase_Amount) as avg_purchase_amount
from customer
Where shipping_type in ('Standard','Express')
group by shipping_type


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as Total_Customers,
round(avg(Purchase_Amount),2) as avg_purchase_amount,
round(sum(Purchase_Amount),2) as Total_Revenue
from customer
group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select top 5 item_purchased,
cast(
    100.0 * sum(case when discount_applied ='Yes' then 1 else 0 end)/count(*)
	as decimal(5,2))  as discount_rate
from customer
group by item_purchased
order by discount_rate desc

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 


"""SELECT 
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS loyalty,
    COUNT(*) AS customer_count
FROM customer
GROUP BY 
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END;"""

with customer_type as(
select customer_id,previous_purchases,
(case
     when previous_purchases = 1 then 'New'
	 when previous_purchases between 2 and 5 then 'Returning'
	 else 'loyal' end ) as customer_segment
from customer 
)
select customer_segment,count(*) as 'number of customer'
from customer_type
group by customer_segment 

--Q8. What are the top 3 most purchased products within each category? 


WITH product_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders
    FROM customer
    GROUP BY category, item_purchased
),
ranked_products AS (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY category 
               ORDER BY total_orders DESC
           ) AS item_rank
    FROM product_counts
)
SELECT *
FROM ranked_products
WHERE item_rank <= 3;



--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select count(customer_id) as repeat_buyers,
subscription_status
from customer 
where previous_purchases > 5
GROUP BY subscription_status

select subscription_status,
count(case 
    when previous_purchases > 5 then customer_id
end) as repeat_buyers
from customer
group by subscription_status
	
--Q10. What is the revenue contribution of each age group
select age_group,
sum(Purchase_Amount) as Revenue
from customer
group by age_group
order by Revenue desc

